import type { ContentPackage } from '../../domain/model'

const contentVersion = '2026.07.foundation'

export const foundationsPackage = {
  schemaVersion: 1,
  contentVersion,
  sectionId: 'foundations',
  course: {
    id: 'kotlin-core',
    title: 'Kotlin Core',
    summary: 'Локальный курс по Kotlin с активным восстановлением и детерминированными проверками.',
    contentVersion,
    moduleIds: ['module.kotlin-foundations'],
    diagnosticExerciseIds: ['exercise.single-choice.val-var', 'exercise.true-false.val-mutability'],
  },
  modules: [
    {
      id: 'module.kotlin-foundations',
      slug: 'kotlin-foundations',
      title: 'Фундамент Kotlin',
      summary: 'Значения, вывод типов, базовая null safety и маленькая модель данных.',
      order: 0,
      lessonIds: ['lesson.kotlin-values'],
      skillIds: ['skill.val-var', 'skill.type-inference', 'skill.null-safety', 'skill.data-class'],
      prerequisiteModuleIds: [],
    },
  ],
  skills: [
    {
      id: 'skill.val-var',
      title: 'val и var',
      summary: 'Выбор неизменяемого или изменяемого binding по намерению кода.',
      area: 'Базовый синтаксис',
      dependencies: [],
    },
    {
      id: 'skill.type-inference',
      title: 'Вывод типов',
      summary: 'Чтение выведенного типа и явная аннотация там, где она помогает.',
      area: 'Типы',
      dependencies: [
        {
          fromSkillId: 'skill.type-inference',
          toSkillId: 'skill.val-var',
          kind: 'prerequisite',
        },
      ],
    },
    {
      id: 'skill.null-safety',
      title: 'Null safety',
      summary: 'Безопасные fallback-выражения без `!!`.',
      area: 'Надежность',
      dependencies: [
        {
          fromSkillId: 'skill.null-safety',
          toSkillId: 'skill.type-inference',
          kind: 'prerequisite',
        },
      ],
    },
    {
      id: 'skill.data-class',
      title: 'Data class',
      summary: 'Короткая модель данных и обновление через `copy`.',
      area: 'Моделирование',
      dependencies: [
        {
          fromSkillId: 'skill.data-class',
          toSkillId: 'skill.val-var',
          kind: 'prerequisite',
        },
      ],
    },
  ],
  concepts: [
    {
      id: 'concept.prefer-val',
      title: 'Предпочитай `val`',
      body: '`val` фиксирует binding после инициализации и делает дальнейшее чтение кода проще.',
      skillIds: ['skill.val-var'],
      misconceptionIds: ['misconception.val-is-constant'],
    },
    {
      id: 'concept.elvis-fallback',
      title: 'Elvis как безопасный fallback',
      body: '`?:` выбирает значение справа, когда выражение слева равно null.',
      skillIds: ['skill.null-safety'],
      misconceptionIds: ['misconception.not-null-assertion'],
    },
  ],
  examples: [
    {
      id: 'example.values.session-counter',
      lessonId: 'lesson.kotlin-values',
      title: 'Имя курса и счетчик попыток',
      code: 'val courseName: String = "Kotlin"\nvar attempts = 1\nattempts += 1',
      explanationId: 'explanation.values.bindings',
    },
  ],
  explanations: [
    {
      id: 'explanation.values.bindings',
      title: 'Binding и изменение',
      body: '`val` не позволяет переназначить binding. `var` нужен только там, где значение действительно меняется.',
      code: 'val name = "Kotlin"\nvar attempts = 1',
    },
    {
      id: 'explanation.null.elvis',
      title: 'Fallback без `!!`',
      body: 'Elvis-оператор выражает fallback явно и не создает runtime-риск из not-null assertion.',
      code: 'val displayName = user.name ?: "Guest"',
    },
    {
      id: 'explanation.data.copy',
      title: 'Обновление data class',
      body: '`copy` сохраняет остальные поля и делает изменение одного свойства явным.',
      code: 'val renamed = user.copy(name = "Ada")',
    },
  ],
  misconceptions: [
    {
      id: 'misconception.val-is-constant',
      title: '`val` не всегда compile-time constant',
      symptom: 'Пользователь считает, что любое `val` равно `const val`.',
      correction: '`val` запрещает переназначение binding, но объект внутри может быть mutable.',
    },
    {
      id: 'misconception.not-null-assertion',
      title: '`!!` как привычный shortcut',
      symptom: 'Пользователь добавляет `!!`, чтобы быстро пройти nullable-ошибку.',
      correction: 'Сначала вырази fallback или явно сузь nullable-тип.',
    },
  ],
  lessons: [
    {
      id: 'lesson.kotlin-values',
      moduleId: 'module.kotlin-foundations',
      title: 'val, var, типы и безопасные значения',
      summary:
        'Один вертикальный срез: прочитать, собрать, исправить и перенести базовые идеи Kotlin.',
      order: 0,
      conceptIds: ['concept.prefer-val', 'concept.elvis-fallback'],
      exampleIds: ['example.values.session-counter'],
      exerciseIds: [
        'exercise.single-choice.val-var',
        'exercise.multiple-choice.immutable-signals',
        'exercise.true-false.val-mutability',
        'exercise.token-ordering.binding',
        'exercise.micro-parsons.counter',
        'exercise.line-parsons.user',
        'exercise.fill-blanks.elvis',
        'exercise.output-prediction.counter',
        'exercise.type-prediction.name',
        'exercise.code-debugging.elvis',
        'exercise.code-writing.greeting',
        'exercise.code-refactoring.var-to-val',
        'exercise.concept-matching.bindings',
        'exercise.execution-tracing.counter',
        'exercise.scenario-transfer.display-name',
        'exercise.project-step.profile-card',
        'exercise.self-check.val-var',
      ],
      skillIds: ['skill.val-var', 'skill.type-inference', 'skill.null-safety', 'skill.data-class'],
      estimatedMinutes: 35,
    },
  ],
  exercises: [
    {
      kind: 'single-choice',
      id: 'exercise.single-choice.val-var',
      lessonId: 'lesson.kotlin-values',
      skillIds: ['skill.val-var'],
      title: 'Выбор binding',
      prompt: 'Какой keyword лучше выбрать для значения, которое не меняется после инициализации?',
      difficulty: 1,
      estimatedSeconds: 30,
      hints: [
        {
          id: 'hint.val-var.intent',
          level: 1,
          body: 'Смотри на намерение: будет ли переназначение?',
        },
      ],
      explanationId: 'explanation.values.bindings',
      options: [
        { id: 'option.val', label: 'val' },
        { id: 'option.var', label: 'var' },
      ],
      checker: { kind: 'single-choice', correctOptionId: 'option.val' },
    },
    {
      kind: 'multiple-choice',
      id: 'exercise.multiple-choice.immutable-signals',
      lessonId: 'lesson.kotlin-values',
      skillIds: ['skill.val-var', 'skill.type-inference'],
      title: 'Сигналы неизменяемости',
      prompt: 'Выбери признаки, что binding можно сделать `val`.',
      difficulty: 2,
      estimatedSeconds: 45,
      hints: [
        {
          id: 'hint.immutable.signals',
          level: 1,
          body: 'Ищи отсутствие последующего присваивания.',
        },
      ],
      explanationId: 'explanation.values.bindings',
      options: [
        { id: 'option.assigned-once', label: 'Значение присваивается один раз' },
        { id: 'option.reassigned-loop', label: 'Значение переназначается в loop' },
        { id: 'option.read-only', label: 'Дальше значение только читается' },
      ],
      checker: {
        kind: 'multiple-choice',
        correctOptionIds: ['option.assigned-once', 'option.read-only'],
        requireExact: true,
      },
    },
    {
      kind: 'true-false',
      id: 'exercise.true-false.val-mutability',
      lessonId: 'lesson.kotlin-values',
      skillIds: ['skill.val-var'],
      title: '`val` и объект',
      prompt: 'Оцени утверждение и объясни коротко.',
      difficulty: 2,
      estimatedSeconds: 45,
      hints: [
        {
          id: 'hint.val.object',
          level: 1,
          body: '`val` относится к binding, а не всегда к объекту.',
        },
      ],
      explanationId: 'explanation.values.bindings',
      statement: '`val users = mutableListOf<String>()` делает список полностью неизменяемым.',
      checker: { kind: 'true-false', expected: false, explanationRequired: true },
    },
    {
      kind: 'token-ordering',
      id: 'exercise.token-ordering.binding',
      lessonId: 'lesson.kotlin-values',
      skillIds: ['skill.val-var'],
      title: 'Порядок токенов',
      prompt: 'Собери объявление `val language: String = "Kotlin"`.',
      difficulty: 1,
      estimatedSeconds: 40,
      hints: [{ id: 'hint.tokens.declaration', level: 1, body: 'Keyword идет перед именем.' }],
      explanationId: 'explanation.values.bindings',
      tokens: ['String', 'language', '"Kotlin"', ':', '=', 'val'],
      checker: {
        kind: 'token-ordering',
        expectedTokens: ['val', 'language', ':', 'String', '=', '"Kotlin"'],
        allowExtraWhitespace: true,
      },
    },
    {
      kind: 'micro-parsons',
      id: 'exercise.micro-parsons.counter',
      lessonId: 'lesson.kotlin-values',
      skillIds: ['skill.val-var'],
      title: 'Счетчик попыток',
      prompt: 'Собери короткий фрагмент с изменяемым счетчиком.',
      difficulty: 2,
      estimatedSeconds: 50,
      hints: [
        { id: 'hint.parsons.counter', level: 1, body: 'Счетчик меняется, значит нужен `var`.' },
      ],
      explanationId: 'explanation.values.bindings',
      fragments: [
        { id: 'fragment.counter.declare', label: 'var attempts = 1' },
        { id: 'fragment.counter.increment', label: 'attempts += 1' },
        { id: 'fragment.counter.print', label: 'println(attempts)' },
      ],
      checker: {
        kind: 'micro-parsons',
        expectedFragmentIds: [
          'fragment.counter.declare',
          'fragment.counter.increment',
          'fragment.counter.print',
        ],
      },
    },
    {
      kind: 'line-parsons',
      id: 'exercise.line-parsons.user',
      lessonId: 'lesson.kotlin-values',
      skillIds: ['skill.data-class'],
      title: 'Порядок строк data class',
      prompt: 'Упорядочь строки так, чтобы сначала была модель, затем ее использование.',
      difficulty: 2,
      estimatedSeconds: 60,
      hints: [
        { id: 'hint.line.user', level: 1, body: 'Тип должен быть объявлен до создания значения.' },
      ],
      explanationId: 'explanation.data.copy',
      lines: [
        { id: 'line.user.copy', label: 'val renamed = user.copy(name = "Ada")' },
        { id: 'line.user.model', label: 'data class User(val id: Long, val name: String)' },
        { id: 'line.user.value', label: 'val user = User(1, "Grace")' },
      ],
      checker: {
        kind: 'line-parsons',
        expectedLineIds: ['line.user.model', 'line.user.value', 'line.user.copy'],
        indentationSensitive: false,
      },
    },
    {
      kind: 'fill-in-the-blanks',
      id: 'exercise.fill-blanks.elvis',
      lessonId: 'lesson.kotlin-values',
      skillIds: ['skill.null-safety'],
      title: 'Заполни Elvis',
      prompt: 'Заполни пропуски, чтобы получить fallback без `!!`.',
      difficulty: 2,
      estimatedSeconds: 45,
      hints: [
        {
          id: 'hint.elvis.operator',
          level: 1,
          body: 'Fallback-оператор состоит из двух символов.',
        },
      ],
      explanationId: 'explanation.null.elvis',
      template: 'val displayName = user.name __operator__ "__fallback__"',
      checker: {
        kind: 'fill-in-the-blanks',
        blanks: [
          { blankId: 'operator', acceptedAnswers: ['?:'], caseSensitive: true },
          { blankId: 'fallback', acceptedAnswers: ['Guest'], caseSensitive: true },
        ],
      },
    },
    {
      kind: 'output-prediction',
      id: 'exercise.output-prediction.counter',
      lessonId: 'lesson.kotlin-values',
      skillIds: ['skill.val-var'],
      title: 'Предскажи вывод',
      prompt: 'Что будет выведено после инкремента счетчика?',
      difficulty: 1,
      estimatedSeconds: 40,
      hints: [
        { id: 'hint.output.counter', level: 1, body: '`+= 1` увеличивает текущее значение.' },
      ],
      explanationId: 'explanation.values.bindings',
      code: 'var attempts = 1\nattempts += 1\nprintln(attempts)',
      checker: { kind: 'output-prediction', expectedOutput: '2', normalizeWhitespace: true },
    },
    {
      kind: 'type-prediction',
      id: 'exercise.type-prediction.name',
      lessonId: 'lesson.kotlin-values',
      skillIds: ['skill.type-inference'],
      title: 'Предскажи тип',
      prompt: 'Какой тип выводится для выражения?',
      difficulty: 1,
      estimatedSeconds: 30,
      hints: [
        { id: 'hint.type.string', level: 1, body: 'Строковый literal выводится как `String`.' },
      ],
      explanationId: 'explanation.values.bindings',
      expression: 'val language = "Kotlin"',
      checker: {
        kind: 'type-prediction',
        expectedType: 'String',
        acceptedAliases: ['kotlin.String'],
      },
    },
    {
      kind: 'code-debugging',
      id: 'exercise.code-debugging.elvis',
      lessonId: 'lesson.kotlin-values',
      skillIds: ['skill.null-safety'],
      title: 'Исправь nullable shortcut',
      prompt: 'Убери опасный `!!` и вырази fallback.',
      difficulty: 3,
      estimatedSeconds: 80,
      hints: [{ id: 'hint.debug.elvis', level: 1, body: 'Замени assertion на Elvis.' }],
      explanationId: 'explanation.null.elvis',
      brokenCode: 'val displayName = user.name!!',
      checker: {
        kind: 'code-debugging',
        requiredFixes: ['use-elvis'],
        forbiddenPatterns: ['!!'],
      },
    },
    {
      kind: 'code-writing',
      id: 'exercise.code-writing.greeting',
      lessonId: 'lesson.kotlin-values',
      skillIds: ['skill.val-var', 'skill.null-safety'],
      title: 'Напиши greeting',
      prompt: 'Создай `val displayName`, который берет nullable name или `"Guest"`.',
      difficulty: 3,
      estimatedSeconds: 90,
      hints: [{ id: 'hint.write.greeting', level: 1, body: 'Нужны `val` и `?:`.' }],
      explanationId: 'explanation.null.elvis',
      starterCode: 'fun greeting(name: String?): String {\n  // return ...\n}',
      checker: {
        kind: 'code-writing',
        requiredConstructs: ['val', '?:'],
        forbiddenConstructs: ['!!'],
        expectedTokens: ['val', 'displayName', '=', 'name', '?:', '"Guest"'],
      },
    },
    {
      kind: 'code-refactoring',
      id: 'exercise.code-refactoring.var-to-val',
      lessonId: 'lesson.kotlin-values',
      skillIds: ['skill.val-var'],
      title: 'Уменьши изменяемость',
      prompt: 'Перепиши код так, чтобы неизменяемые bindings стали `val`.',
      difficulty: 3,
      estimatedSeconds: 80,
      hints: [
        { id: 'hint.refactor.val', level: 1, body: 'Проверь, что действительно переназначается.' },
      ],
      explanationId: 'explanation.values.bindings',
      originalCode: 'var course = "Kotlin"\nvar attempts = 1\nattempts += 1',
      checker: {
        kind: 'code-refactoring',
        preservedBehaviorCases: ['attempts-still-increments'],
        requiredChanges: ['course-to-val', 'attempts-remains-var'],
      },
    },
    {
      kind: 'concept-matching',
      id: 'exercise.concept-matching.bindings',
      lessonId: 'lesson.kotlin-values',
      skillIds: ['skill.val-var'],
      title: 'Сопоставь понятия',
      prompt: 'Соедини понятие с его ролью.',
      difficulty: 1,
      estimatedSeconds: 45,
      hints: [{ id: 'hint.match.bindings', level: 1, body: '`var` допускает переназначение.' }],
      explanationId: 'explanation.values.bindings',
      leftItems: [
        { id: 'left.val', label: 'val' },
        { id: 'left.var', label: 'var' },
      ],
      rightItems: [
        { id: 'right.readonly-binding', label: 'binding без переназначения' },
        { id: 'right.mutable-binding', label: 'binding с переназначением' },
      ],
      checker: {
        kind: 'concept-matching',
        pairs: [
          { leftId: 'left.val', rightId: 'right.readonly-binding' },
          { leftId: 'left.var', rightId: 'right.mutable-binding' },
        ],
      },
    },
    {
      kind: 'execution-tracing',
      id: 'exercise.execution-tracing.counter',
      lessonId: 'lesson.kotlin-values',
      skillIds: ['skill.val-var'],
      title: 'Проследи значения',
      prompt: 'Запиши значения счетчика после каждой строки.',
      difficulty: 2,
      estimatedSeconds: 60,
      hints: [{ id: 'hint.trace.counter', level: 1, body: 'После объявления значение равно 1.' }],
      explanationId: 'explanation.values.bindings',
      code: 'var attempts = 1\nattempts += 1\nattempts += 2',
      checkpoints: ['after-declare', 'after-first-increment', 'after-second-increment'],
      checker: {
        kind: 'execution-tracing',
        expectedSteps: ['attempts=1', 'attempts=2', 'attempts=4'],
      },
    },
    {
      kind: 'scenario-based-transfer',
      id: 'exercise.scenario-transfer.display-name',
      lessonId: 'lesson.kotlin-values',
      skillIds: ['skill.null-safety'],
      title: 'Перенос в UI-сценарий',
      prompt: 'Пользователь может не указать имя. Опиши безопасную Kotlin-модель fallback.',
      difficulty: 4,
      estimatedSeconds: 120,
      hints: [
        { id: 'hint.transfer.display-name', level: 1, body: 'Нужен nullable input и fallback.' },
      ],
      explanationId: 'explanation.null.elvis',
      scenario: 'Экран профиля должен показать имя или "Guest", если поле отсутствует.',
      checker: {
        kind: 'scenario-based-transfer',
        requiredConceptIds: ['concept.elvis-fallback'],
        acceptedSolutionIds: ['solution.display-name.elvis'],
      },
    },
    {
      kind: 'project-step',
      id: 'exercise.project-step.profile-card',
      lessonId: 'lesson.kotlin-values',
      skillIds: ['skill.data-class', 'skill.null-safety'],
      title: 'Шаг проекта: профиль',
      prompt: 'Опиши модель профиля и безопасное displayName-свойство.',
      difficulty: 4,
      estimatedSeconds: 180,
      hints: [
        { id: 'hint.project.profile', level: 1, body: 'Сочетай `data class` и computed fallback.' },
      ],
      explanationId: 'explanation.data.copy',
      projectContext: 'Мини-проект локального профиля без backend.',
      checker: {
        kind: 'project-step',
        requiredArtifacts: ['Profile data class', 'displayName fallback'],
        acceptanceRules: ['uses data class', 'does not use !!'],
      },
    },
    {
      kind: 'self-check-question',
      id: 'exercise.self-check.val-var',
      lessonId: 'lesson.kotlin-values',
      skillIds: ['skill.val-var'],
      title: 'Самопроверка',
      prompt: 'Коротко объясни, когда ты осознанно выберешь `var`.',
      difficulty: 1,
      estimatedSeconds: 60,
      hints: [
        {
          id: 'hint.self.var',
          level: 1,
          body: '`var` нужен не "на всякий случай", а при переназначении.',
        },
      ],
      explanationId: 'explanation.values.bindings',
      question: 'Когда `var` лучше `val`?',
      checker: {
        kind: 'self-check-question',
        requiredReflectionIds: ['reflection.intent', 'reflection.reassignment'],
        minLength: 24,
      },
    },
  ],
} satisfies ContentPackage

export default foundationsPackage
